class SpeakCareEmrTables:
        # Table names
    
    """
      The followoing are table names as they appear in the Airtable database 
      Every table that should be accessed by the API should be added here
      The table names should be exactly as they appear in the Airtable database
      #TODO: load tables dynamically from the API
    """
    ### People ###
    PATIENTS_TABLE = 'Patients'
    NURSES_TABLE = 'Nurses'
    DOCTORS_TABLE = 'Doctors'
    
    ### Medical Records ###
    VITALS_TABLE = 'Vitals'
    WEIGHTS_TABLE = 'Weights'
    BLOOD_PRESSURES_TABLE = 'Blood Pressures'
    BLOOD_SUGARS_TABLE = 'Blood Sugars'
    HEIGHTS_TABLE = 'Heights'
    TEMPERATURES_TABLE = 'Temperatures'
    O2_SATURATIONS_TABLE = 'O2 Saturations'
    PULSES_TABLE = 'Pulses'
    RESPIRATION_TABLE = 'Respiration'
    EPISODES_TABLE = 'Episodes'
    PROGRESS_NOTES_TABLE = 'Progress Notes'
    
    ### Assessments ###
    # Admission
    ADMISSION_TABLE = 'Admission'
    ADMISSION_SECTION_1_DEMOGRAPHCS_TABLE   = 'Admission: SECTION 1. DEMOGRAPHICS'
    ADMISSION_SECTION_2_VITALS_TABLE        = 'Admission: SECTION 2. VITALS-ALLERGIES'
    ADMISSION_SECTION_3_SKIN_TABLE          = 'Admission: SECTION 3. SKIN CONDITION'
    ADMISSION_SECTION_4_PHYSICAL_TABLE      = 'Admission: SECTION 4. PHYSICAL / ADL / COMMUNICATION STATUS'
    ADMISSION_SECTION_5_BOWEL_BLADDER_TABLE = 'Admission: SECTION 5. BOWEL-BLADDER EVALUATION'
    ADMISSION_SECTION_6_PSYCHOSOCIAL_TABLE  = 'Admission: SECTION 6. PSYCHOSOCIAL ASPECTS'
    ADMISSION_SECTION_7_DISCHARGE_TABLE     = 'Admission: SECTION 7. DISCHARGE EVALUATION'
    ADMISSION_SECTION_8_FACILITY_TABLE      = 'Admission: SECTION 8. ORIENTATION TO FACILITY'

    # Fall Risk Screen
    FALL_RISK_SCREEN_TABLE = 'Fall Risk Screen'
    FALL_RISK_SCREEN_SECTION_1_TABLE = 'Fall Risk Screen: SECTION 1'


    # Harmony (Holy Name) tables
    HARMONY_VITALS_TABLE = 'Harmony Vitals'
    LABOR_ADMISSION_SECTION_1_TABLE='Labor Admission Section 1'
    #LABOR_ADMISSION_SECTION_2_TABLE='Labor Admission Section 2'
    LABOR_ADMISSION_SECTION_3_TABLE='Labor Admission Section 3'
    LABOR_ADMISSION_SECTION_4_TABLE='Labor Admission Section 4'
    LABOR_ADMISSION_SECTION_5_TABLE='Labor Admission Section 5'
    MED_SRG_NURSING_ASSESSMENT_TABLE='Harmony Med/Surg Nursing Assessment'
    CRITICAL_CARE_NURSING_ASSESSMENT_TABLE='Harmony Critical Care Nursing Assessment'
    SPORT_PERFORMANCE_ASSESSMENT_1='Sport Performance Assessment 1'

    SPORT_PERFORMANCE_ASSESSMENT_2='Sport Performance Assessment 2'
    SPORT_2_TEST='Sport Performance Assessment 2 Test'
    STAR_EXCURSION_BALANCE_TEST_L_FOOT_BALANCE_R_FOOT_REACH = 'STAR EXCURSION BALANCE TEST L FOOT BALANCE - R FOOT REACH'
    STAR_EXCURSION_BALANCE_TEST_R_FOOT_BALANCE_L_FOOT_REACH = 'STAR EXCURSION BALANCE TEST R FOOT BALANCE - L FOOT REACH'
    HAND_STAR_EXCURSION_BALANCE_TEST_L_FOOT_BALANCE_R_HAND_REACH='HAND STAR EXCURSION BALANCE TEST L FOOT BALANCE - R HAND REACH'
    HAND_STAR_EXCURSION_BALANCE_TEST_R_FOOT_BALANCE_L_HAND_REACH='HAND STAR EXCURSION BALANCE TEST R FOOT BALANCE - L HAND REACH'

    SPORT_PERFORMANCE_ASSESSMENT_3='Sport Performance Assessment 3'
    SPORT_3_TEST='Sport Performance Assessment 3 Test'
    GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_ANTERIOR='GLOBAL/INTEGRATED ASSESSMENT 3DMAPS - LIMITING AREAS - ANTERIOR'
    GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_LATERAL_OS='GLOBAL/INTEGRATED ASSESSMENT 3DMAPS - LIMITING AREAS - LATERAL OS'
    GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_LATERAL_SS='GLOBAL/INTEGRATED ASSESSMENT 3DMAPS - LIMITING AREAS - LATERAL SS'
    GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_POSTERIOR='GLOBAL/INTEGRATED ASSESSMENT 3DMAPS - LIMITING AREAS - POSTERIOR'
    GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_ROTATIONAL_OS='GLOBAL/INTEGRATED ASSESSMENT 3DMAPS - LIMITING AREAS - ROTATIONAL OS'
    GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_ROTATIONAL_SS='GLOBAL/INTEGRATED ASSESSMENT 3DMAPS - LIMITING AREAS - ROTATIONAL SS'

    SPORT_PERFORMANCE_ASSESSMENT_4='Sport Performance Assessment 4'
    LOCAL_ASSESSMENT_ENDURANCE='LOCAL ASSESSMENT - ENDURANCE'
    LOCAL_ASSESSMENT_STABILITY='LOCAL ASSESSMENT - STABILITY'
    LOCAL_ASSESSMENT_STRENGTH='LOCAL ASSESSMENT - STRENGTH'

    HARMONY_EXAM_SECTION_1_TABLE = 'Harmony.ExamSection_1'
    HARMONY_EXAM_SECTION_2_TABLE = 'Harmony.ExamSection_2'
    HARMONY_EXAM_SECTION_3_TABLE = 'Harmony.ExamSection_3'
    HARMONY_SAFETY_STATUS_SECTION_TABLE = 'Harmony.SafetyStatusSection'
    HARMONY_TREATMENTS_SECTION_TABLE = 'Harmony.TreatmentsSection'

    # Grove (Millennial) tables
    GROVE_ASSESSMENT_DETAILS_TABLE = 'Grove_Assessment_Details'
    MHCS_NURSING_DAILY_SKILLED_NOTE_TABLE = 'MHCS.Nursing_Daily_Skilled_Note'
    MHCS_ADMISSION_DETAILS_TABLE = 'MHCS.Admission_Details'
    MHCS_EINTERACT_EVALUATION_TABLE = 'MHCS.eINTERACT_Change_in_Condition_Evaluation'
    MHCS_NEUROLOGICAL_EVALUATION_TABLE = 'MHCS.Neurological_Evaluation'


    MHCS_ADMISSION_AIMS_TABLE = "MHCS.Admission_AIMS"
    MHCS_ADMISSION_ALCOHOL_TOBACCO_USE_TABLE = "MHCS.Admission_Alcohol_Tobacco_Use"
    MHCS_ADMISSION_BRADEN_TABLE = "MHCS.Admission_Braden"
    MHCS_ADMISSION_EDUCATION_TABLE = "MHCS.Admission_Education"
    MHCS_ADMISSION_ELOPEMENT_TABLE = "MHCS.Admission_Elopement"
    MHCS_ADMISSION_ENABLER_BED_RAIL_SCREEN_TABLE = "MHCS.Admission_Enabler_Bed_Rail_Screen"
    MHCS_ADMISSION_EVALUATION_OF_BODY_SYSTEMS_TABLE_1 = "MHCS.Admission_Evaluation_of_Body_Systems_1"
    MHCS_ADMISSION_EVALUATION_OF_BODY_SYSTEMS_TABLE_2 = "MHCS.Admission_Evaluation_of_Body_Systems_2"
    MHCS_ADMISSION_FALL_SCREEN_TABLE = "MHCS.Admission_Fall_Screen"
    MHCS_ADMISSION_INFECTIONS_TABLE = "MHCS.Admission_Infections"
    MHCS_ADMISSION_INTERVENOUS_ACCESS_DEVICES_TABLE = "MHCS.Admission_Intravenous_Access_Devices"
    MHCS_ADMISSION_MEDICATIONS_TABLE = "MHCS.Admission_Medications"
    MHCS_ADMISSION_PAIN_TABLE = "MHCS.Admission_Pain"


    
    

    # TODO: Table and sections names need to be loaded dyanically from the API
    """
      The followoing are the list of tables that we are actively supporting in the API
      In order for a table to be accessed by the API, it should be added to this list
      # TODO: Table and sections names need to be loaded dyanically from the API
    """
    EMR_TABLES = [
        PATIENTS_TABLE,
        NURSES_TABLE,
        DOCTORS_TABLE,
        EPISODES_TABLE, 
        PROGRESS_NOTES_TABLE,
        ADMISSION_TABLE,
        FALL_RISK_SCREEN_TABLE,
        VITALS_TABLE,
        HARMONY_VITALS_TABLE,
        LABOR_ADMISSION_SECTION_1_TABLE,
        #LABOR_ADMISSION_SECTION_2_TABLE,
        LABOR_ADMISSION_SECTION_3_TABLE,
        LABOR_ADMISSION_SECTION_4_TABLE,
        LABOR_ADMISSION_SECTION_5_TABLE,
        MED_SRG_NURSING_ASSESSMENT_TABLE,
        CRITICAL_CARE_NURSING_ASSESSMENT_TABLE,
        SPORT_PERFORMANCE_ASSESSMENT_1,
        SPORT_PERFORMANCE_ASSESSMENT_2,
        SPORT_PERFORMANCE_ASSESSMENT_3,
        SPORT_PERFORMANCE_ASSESSMENT_4,
        SPORT_2_TEST,
        SPORT_3_TEST,

        # Harmony
        HARMONY_EXAM_SECTION_1_TABLE,
        HARMONY_EXAM_SECTION_2_TABLE,
        HARMONY_EXAM_SECTION_3_TABLE,
        HARMONY_SAFETY_STATUS_SECTION_TABLE,
        HARMONY_TREATMENTS_SECTION_TABLE,
        
        # Grove
        GROVE_ASSESSMENT_DETAILS_TABLE,
        MHCS_NURSING_DAILY_SKILLED_NOTE_TABLE,
        MHCS_ADMISSION_DETAILS_TABLE,
        MHCS_EINTERACT_EVALUATION_TABLE,
        MHCS_NEUROLOGICAL_EVALUATION_TABLE,
        MHCS_ADMISSION_AIMS_TABLE,
        MHCS_ADMISSION_ALCOHOL_TOBACCO_USE_TABLE,
        MHCS_ADMISSION_BRADEN_TABLE,
        MHCS_ADMISSION_EDUCATION_TABLE,
        MHCS_ADMISSION_ELOPEMENT_TABLE,
        MHCS_ADMISSION_ENABLER_BED_RAIL_SCREEN_TABLE,
        MHCS_ADMISSION_EVALUATION_OF_BODY_SYSTEMS_TABLE_1,
        MHCS_ADMISSION_EVALUATION_OF_BODY_SYSTEMS_TABLE_2,
        MHCS_ADMISSION_FALL_SCREEN_TABLE,
        MHCS_ADMISSION_INFECTIONS_TABLE,
        MHCS_ADMISSION_INTERVENOUS_ACCESS_DEVICES_TABLE,
        MHCS_ADMISSION_MEDICATIONS_TABLE,
        MHCS_ADMISSION_PAIN_TABLE,
        
        # WEIGHTS_TABLE, 
        # BLOOD_PRESSURES_TABLE, 
        # BLOOD_SUGARS_TABLE, 
        # HEIGHTS_TABLE, 
        # TEMPERATURES_TABLE,
        # O2_SATURATIONS_TABLE,
        # PULSES_TABLE,
        # RESPIRATION_TABLE
    ]

    """
      The followoing are the dictionary of multi-section tables.
      A table that has sections should be added to this dict with its sections as a list.
      #TODO: load tables dynamically from the API
    """
    TABLE_SECTIONS = { 
            ADMISSION_TABLE: [
                ADMISSION_SECTION_1_DEMOGRAPHCS_TABLE, 
                ADMISSION_SECTION_2_VITALS_TABLE, 
                ADMISSION_SECTION_3_SKIN_TABLE, 
                ADMISSION_SECTION_4_PHYSICAL_TABLE, 
                ADMISSION_SECTION_5_BOWEL_BLADDER_TABLE, 
                ADMISSION_SECTION_6_PSYCHOSOCIAL_TABLE,
                ADMISSION_SECTION_7_DISCHARGE_TABLE,
                ADMISSION_SECTION_8_FACILITY_TABLE
            ],            
            FALL_RISK_SCREEN_TABLE: [FALL_RISK_SCREEN_SECTION_1_TABLE],
            VITALS_TABLE: [
                WEIGHTS_TABLE,
                BLOOD_PRESSURES_TABLE,
                BLOOD_SUGARS_TABLE,
                HEIGHTS_TABLE,
                TEMPERATURES_TABLE,
                O2_SATURATIONS_TABLE,
                PULSES_TABLE,
                RESPIRATION_TABLE
            ],
            SPORT_2_TEST: [
                STAR_EXCURSION_BALANCE_TEST_L_FOOT_BALANCE_R_FOOT_REACH,
                STAR_EXCURSION_BALANCE_TEST_R_FOOT_BALANCE_L_FOOT_REACH,
                HAND_STAR_EXCURSION_BALANCE_TEST_L_FOOT_BALANCE_R_HAND_REACH,
                HAND_STAR_EXCURSION_BALANCE_TEST_R_FOOT_BALANCE_L_HAND_REACH,
            ],

            # SPORT_PERFORMANCE_ASSESSMENT_2: [
            #     STAR_EXCURSION_BALANCE_TEST_L_FOOT_BALANCE_R_FOOT_REACH,
            #     STAR_EXCURSION_BALANCE_TEST_R_FOOT_BALANCE_L_FOOT_REACH,
            #     HAND_STAR_EXCURSION_BALANCE_TEST_L_FOOT_BALANCE_R_HAND_REACH,
            #     HAND_STAR_EXCURSION_BALANCE_TEST_R_FOOT_BALANCE_L_HAND_REACH,
            # ],
            
            # SPORT_PERFORMANCE_ASSESSMENT_3: [
            SPORT_3_TEST: [
                GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_ANTERIOR,
                GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_LATERAL_OS,
                GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_LATERAL_SS,
                GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_POSTERIOR,
                GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_ROTATIONAL_OS,
                GLOBAL_INTEGRATED_ASSESSMENT_3DMAPS_LIMITING_AREAS_ROTATIONAL_SS,
            ],
            # SPORT_PERFORMANCE_ASSESSMENT_4: [
            #     LOCAL_ASSESSMENT_ENDURANCE,
            #     LOCAL_ASSESSMENT_STABILITY,
            #     LOCAL_ASSESSMENT_STRENGTH,
            # ]
    }

    PERSON_TABLES = [PATIENTS_TABLE, NURSES_TABLE, DOCTORS_TABLE]
